image: Visual Studio 2017
configuration: Release
before_build:
- nuget restore
after_build:
- cmd: dotnet pack DawgSharp/DawgSharp.csproj --no-build -c Release
artifacts:
- path: 'DawgSharp\**\*.nupkg'
  name: Nuget
